### ISSUE TITLE
Missing some apis for orders, trades, terms for lending apis

### ISSUE THREAD

**Issue by thanhvk** [tomochain/tomox-sdk#126]
- ~~`/orders`: to get the user's order list.~~ (ok)
- `/trades:` to get the user's trade list.
- ~~`/terms`: to get term list.~~ (ok)

**Comment by thanhvk** [comment]
```/trades/history``` need to change from requiring ```term``` and ```lendingToken``` to optional.

**Comment by thanhson1085** [comment]
Yep, I just take a look. Seems it doesn't requires it.
Just mistake in tomoxjs

**Comment by thanhson1085** [comment]
I have fixed it devnet.

**Comment by thanhvk** [comment]
- In the ```/orders``` api ```tradeId``` always is ```0``` 
- The ```/trades/history``` api and ```lending_trades``` websocket also missing ```tradeId```

we need to fix it

**Comment by thanhvk** [comment]
The ```lending_trades``` websocket return empty ```tradeID``` in case type is ```UPDATE``` (type ```INIT`` is ok) as below:

![lending_trades_empty_tradeID](https://user-images.githubusercontent.com/11411161/77276459-50fc9180-6ced-11ea-95b7-201f2cd546d3.png)

**Comment by thanhson1085** [comment]
I have fixed websocket tradeid, thank you for the report

**Comment by thanhson1085** [comment]
Can we close this issue @thanhvk ?
