### ISSUE TITLE
The lending_orders websocket return incorrect type

### ISSUE THREAD

**Issue by thanhvk** [tomochain/tomox-sdk#128]
When creating a new lending order or cancel an lending order the lending_orders websocket return incorrect type as below:

![lending_orders_incorrect_type](https://user-images.githubusercontent.com/11411161/77385008-7b1b8580-6db9-11ea-8a4d-fe48fe6ffd77.png)

Expect return correct type as below:
```
LENDING_ORDER_ADDED            = "LENDING_ORDER_ADDED"
LENDING_ORDER_FILLED           = "LENDING_ORDER_FILLED"
LENDING_ORDER_PARTIALLY_FILLED = "LENDING_ORDER_PARTIALLY_FILLED"
LENDING_ORDER_CANCELLED        = "LENDING_ORDER_CANCELLED"
LENDING_ORDER_REJECTED         = "LENDING_ORDER_REJECTED"
```
https://github.com/tomochain/tomox-sdk/blob/master/types/wsmsg.go

**Comment by thanhson1085** [comment]
I have updated the ws message type.
