### ISSUE TITLE
Can't connect wallet to DEX

### ISSUE THREAD

**Issue by Dr-Shin** [tomochain/tomox-sdk#140]
Hello,
i can't unlock wallet on https://trade.visiodex.com/unlock , i tryed metamask and private key, both return an error in console
`engine.js:24 GET https://trade.visiodex.com/api/account/0x42db3FD6A0c68389A1935D1bfF6479172bcB7426 502 (Bad Gateway)`

Nginx logs : 
`2020/06/10 12:20:21 [error] 20051#20051: *79 upstream prematurely closed connection while reading response header from upstream, client: 85.171.121.70, server: trade.visiodex.com, request: "GET /api/account/0x42db3FD6A0c68389A1935D1bfF6479172bcB7426 HTTP/1.1", upstream: "http://127.0.0.1:8080/api/account/0x42db3FD6A0c68389A1935D1bfF6479172bcB7426", host: "trade.visiodex.com", referrer: "https://trade.visiodex.com/unlock"`

**Comment by thanhson1085** [comment]
Seems your fullnode was down that time, then dex backend can not get the balances

**Comment by Dr-Shin** [comment]
> 
> 
> Seems your fullnode was down that time, then dex backend can not get the balances

Seems that fullnode is down again, but it says it's online with `pm2 status` 
How can it be down and online at the same time ?

**Comment by Dr-Shin** [comment]
I restarted it and it went fully back from #21,800,000 block to block #20,600,000...
i had log ssh on screen, it went back 1 block after 1, displaying thousands and thousands of lines with this : 
`rewound blockchain to past state` 
`error when init new lending/trading state trie`

**Comment by thanhson1085** [comment]
Issue with tomox state data directory, upgrade your fullnode to the latest version.

**Comment by Dr-Shin** [comment]
Ok will do, can you update one command install  `bash <(curl -sSL https://tomochain.com/get-tomox.sh) ` please ?

**Comment by thanhson1085** [comment]
Ok, wait for your node sync full, it works OK in my side.
