### ISSUE TITLE
Missing fields in get market response

### ISSUE THREAD

**Issue by pqv199x** [tomochain/tomox-sdk#143]
Expect: 
![image](https://user-images.githubusercontent.com/24842503/84990899-01085c00-b170-11ea-95a8-a0eaf2375446.png)

Current:

> {
        "askPrice": "0",
        "bidPrice": "0",
        "close": "4553",
        "closeBaseUsd": "0.4291",
        "count": "1593",
        "high": "4647",
        "low": "4405",
        "open": "4461",
        "orderCount": "0",
        "orderVolume": "0",
        "pair": {
            "baseToken": "0x0000000000000000000000000000000000000001",
            "pairName": "TOMO/BTC",
            "quoteToken": "0xAE44807D8A9CE4B30146437474Ed6fAAAFa1B809"
        },
        "price": "0",
        "rank": 0,
        "timestamp": 0,
        "volume": "195917753"
    }

**Comment by thanhson1085** [comment]
fixed https://github.com/tomochain/tomox-sdk/commit/ac67009823df9a4ceb89d25b1ad1b18a077aa6fe
