### ISSUE TITLE
panic: E11000 duplicate key error collection

### ISSUE THREAD

**Issue by Dr-Shin** [tomochain/tomox-sdk#147]
Hi,
i got an issue which come back again and again...
On 19th june from pm2 log : 
tomox-sdk  | panic: E11000 duplicate key error collection: tomodex.orders inde                                                                                                                                                             x: hash_1 dup key: { hash: "0x0061d1169f15bb504425021c2d01344fdb983cb2426f548423                                                                                                                                                             561f3b800e28de" }

Today from pm2 log : 
tomox-sdk  | panic: E11000 duplicate key error collection: tomodex.orders inde                                                               x: hash_1 dup key: { hash: "0x0662ac5fbc781630fea45f537bc5438b8a95a03888625ca80c                                                               9ddfb039604744" }

Each time, i have to delete docker container and volume and proceed to a reinstallation of mangodb.

**Comment by nghiatomo** [comment]
fixed in https://github.com/tomochain/tomox-sdk/commit/031db915ddd90d5846c37061b7a324095e14545c

**Comment by Dr-Shin** [comment]
Is this get fixed with fast install procedure? i got the same error again, how can i update it ?

**Comment by thanhson1085** [comment]
Now you just need to run the quickstart script to update tomox-sdk to v1.2.3

**Comment by Dr-Shin** [comment]
@thanhson1085 awesome, thanks
