### ISSUE TITLE
order disappear, can't cancel and funds locked in orders

### ISSUE THREAD

**Issue by Dr-Shin** [tomochain/tomox-sdk#149]
Hello,
a lot of Open Orders are disappearing after few days, so we can't cancel them anymore.

For example : 
https://scan.tomochain.com/orders/0xb225ea0e18c70b354c18770eff4d9a7ccd83974919f4bf3358c6303d2d0a8ac3
an order i put on 2 months ago :

![order](https://user-images.githubusercontent.com/65484728/90409673-c193b880-e0a9-11ea-8605-fab6d5d9b24e.jpg)

As you can see, order is appearing on orderbook while it's absent from Open orders, so i can't cancel it..
I don't see them locked in VisioDEX but if i log in TomoDEX, those tomo are locked in orders

![stuck in orders](https://user-images.githubusercontent.com/65484728/90409800-ec7e0c80-e0a9-11ea-89a2-89871611c8f8.jpg)

So my wallet can't interact on Tomo paires without at least 379.73 + 1 Tomo

Someone else complains about this situation with a stuck open order which disappeared : 
https://scan.tomochain.com/orders/0x1132b29b1788275d5524c012e6b05637ed36ca2c25b9245f62d197a9e8b1d36e

It was only from 2 days ago

**Comment by thanhson1085** [comment]
Ok, we will investigate it.

**Comment by Dr-Shin** [comment]
Ok thanks, will it affect dex? cause i can't connect to socket anymore

**Comment by Dr-Shin** [comment]
Any way to cancel those order manually while you investigate ?

**Comment by thanhson1085** [comment]
you can check your mongo database, make sure that the order is stored in db.

**Comment by thanhson1085** [comment]
Seems NOT, `https://trade.visiodex.com/api/orders?address=0x42db3fd6a0c68389a1935d1bff6479172bcb7426&orderStatus=OPEN`

But It shows here: https://dex.tomochain.com/api/orders?address=0x42db3fd6a0c68389a1935d1bff6479172bcb7426&orderStatus=OPEN&relayerAddress=0x83c7399d01e3e1c20e5ffd7957c8666d73c1ad9b

Your DB missed the order, you need to re-run the fullnode mongodb

**Comment by Dr-Shin** [comment]
Ok, how i proceed? i just delete the docker volume and reinstall it? Why those orders disappeared from DB ?

**Comment by thanhson1085** [comment]
Run from scratch in the new server, then point the domain to the new server

**Comment by Dr-Shin** [comment]
from scratch without snapshot ?

**Comment by thanhson1085** [comment]
Run quick-start script, then remove tomox datadir, restart fullnode

**Comment by Dr-Shin** [comment]
Ok that's what i did, 4millions block to go now.

We need an alternative to fix this kind of issue, what would happened in few months/years when blockchain will be way more heavy? it will be impossible to stop node for days to catch 10-20-100 millions block.

I thought i was safe with my chaindata snapshots but obviously, i'm not.

Now i understand why older order disappeared as we migrated to new server a month a go, but it doesn't explain why this order https://scan.tomochain.com/orders/0x1132b29b1788275d5524c012e6b05637ed36ca2c25b9245f62d197a9e8b1d36e disappeared / was missed by DB.

**Comment by thanhson1085** [comment]
You do not need to shutdown business to fix the minor issue.

The old server is OK with the minor bug. You run a new server, setup the re-sync. When the new server is ready, you switch the domain to the new one with zero-downtime.

I do not have mongodb backup for now.

I suggest you a solution to save the time. You just need to run the frontend in your server and use our backend. So you do not need to run fullnode, mongodb, sdk, you just need a small server to run the frontend.

**Comment by Dr-Shin** [comment]
Ok i'll try that way until i can fix that node issue, so people who are stuck can finally remove their order.

How do i use your backend ?

**Comment by thanhson1085** [comment]
2 steps:
- Point CNAME record for a sub domain (e.g api.visiodex.com) to `cn.tomochain.com`
- Update `.env` file in your FE code with the domain
```
REACT_APP_ENGINE_HTTP_URL='https://api.visiodex.com/api'
REACT_APP_ENGINE_WS_URL='https://api.visiodex.com/socket'
```
And rebuild the FE.

Let me know the domain when you finish the step one. I need to know the domain do config our backend.

**Comment by Dr-Shin** [comment]
Ok the domain is `api.visiodex.com`, it's done.
I'll update FE.

**Comment by thanhson1085** [comment]
OK, you go relayer.tomochain.com, unlock the owner wallet. and update the dex url info to `https://api.visiodex.com`, it should be work automatically.

**Comment by thanhson1085** [comment]
If socket does NOT work, try to update config:
```
REACT_APP_ENGINE_WS_URL='wss://api.visiodex.com/socket'
```

**Comment by Dr-Shin** [comment]
My associate is on vacation so i'll have to wait him to change relayer information.

Still trying to sync the node, it's really really slow, log is full of :

9|tomox-fullnode  | DEBUG[08-28|11:56:35] Discarded propagated block, too far away peer=f9ff0f88c8f2b39e number=25026866 hash=859477…0031c8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     distance=1902449


9|tomox-fullnode  | DEBUG[08-28|11:56:35] Discarded propagated block, too far away peer=0f0d344b874fbbf0 number=25026867 hash=f736ec…975f7a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     distance=1902450


9|tomox-fullnode  | DEBUG[08-28|11:56:35] Discarded propagated block, too far away peer=917f8dc30d9247a8 number=25026867 hash=f736ec…975f7a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     distance=1902450


9|tomox-fullnode  | DEBUG[08-28|11:56:35] Discarded propagated block, too far away peer=e69e47bb05914418 number=25026867 hash=f736ec…975f7a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     distance=1902450


9|tomox-fullnode  | DEBUG[08-28|11:56:35] Discarded propagated block, too far away peer=12958408819f4df3 number=25026867 hash=f736ec…975f7a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     distance=1902450


9|tomox-fullnode  | DEBUG[08-28|11:56:35] Discarded propagated block, too far away peer=f51cd6ea9683a608 number=25026867 hash=f736ec…975f7a

**Comment by Dr-Shin** [comment]
Can't load any pair on spot trading after logging with metamask with your solution, displaying "Cannot read proprerty 'baseTokenDecimals' of undefined.

**Comment by Dr-Shin** [comment]
Relayer information are modified, but impossible to load a pair on spot trading when i connect with metamask or with tomowallet on dapp, it displays "Cannot read property 'baseTokenDecimals' of undefined".

**Comment by thanhson1085** [comment]
Did you update the `.env` and rebuild FE?
```
REACT_APP_ENGINE_HTTP_URL='https://api.visiodex.com/api'
REACT_APP_ENGINE_WS_URL='wss://api.visiodex.com/socket'
```

**Comment by Dr-Shin** [comment]
> 
> 
> Did you update the `.env` and rebuild FE?
> 
> ```
> REACT_APP_ENGINE_HTTP_URL='https://api.visiodex.com/api'
> REACT_APP_ENGINE_WS_URL='wss://api.visiodex.com/socket'
> ```

Yes

**Comment by thanhson1085** [comment]
> Relayer information are modified, but impossible to load a pair on spot trading when i connect with metamask or with tomowallet on dapp, it displays "Cannot read property 'baseTokenDecimals' of undefined".

It works in my side. I think you should clear the cache by change the version in `.env` file:
```
REACT_APP_DEX_VERSION=xxx
```

**Comment by Dr-Shin** [comment]
Did you try to login? it's not working after being logged on.

I changed the version in `.env` file, but it's not working.

**Comment by thanhson1085** [comment]
Yep, logged in Ok with metamask. You should create another issue with the details, we can investigate more. thank you.
