### ISSUE TITLE
closeTime, openTime is not correct for OHLCV api

### ISSUE THREAD

**Issue by phucngh** [tomochain/tomox-sdk#73]
https://dex.devnet.tomochain.com/api/ohlcv?baseToken=0x4d7eA2cE949216D6b120f3AA10164173615A2b6C&quoteToken=0x0000000000000000000000000000000000000001&timeInterval=5m&from=1566493200&to=1566543600

Return data:

`{"close":"20439780000000000000000","closeTime":"0001-01-01T00:00:00Z","count":"10","high":"20492490000000000000000","low":"20418540000000000000000","open":"20418540000000000000000","openTime":"0001-01-01T00:00:00Z","pair":{"baseToken":"0x4d7eA2cE949216D6b120f3AA10164173615A2b6C","pairName":"BTC/TOMO","quoteToken":"0x0000000000000000000000000000000000000001"},"timestamp":1566527100000,"volume":"24441888802147940"},{"close":"20515760000000000000000","closeTime":"0001-01-01T00:00:00Z","count":"5","high":"20515760000000000000000","low":"20515760000000000000000","open":"20515760000000000000000","openTime":"0001-01-01T00:00:00Z","pair":{"baseToken":"0x4d7eA2cE949216D6b120f3AA10164173615A2b6C","pairName":"BTC/TOMO","quoteToken":"0x0000000000000000000000000000000000000001"},"timestamp":1566527400000,"volume":"20000000000000000"},`
Allways format:
**0001-01-01T00:00:00Z**

**Comment by nghiatomo** [comment]
fixed in commit f3ab6e53407025d9d0d1f44111f0bea0d367b84a
