### ISSUE TITLE
OHLCV api: Range of candle is not correct

### ISSUE THREAD

**Issue by phucngh** [tomochain/tomox-sdk#74]
url for candle 7m:
https://dex.devnet.tomochain.com/api/ohlcv?baseToken=0x4d7eA2cE949216D6b120f3AA10164173615A2b6C&quoteToken=0x0000000000000000000000000000000000000001&timeInterval=7m&from=1566493200&to=1566543600

Data Return:
`{"close":"20515640000000000000000","closeTime":"0001-01-01T00:00:00Z","count":"23","high":"20515900000000000000000","low":"20515640000000000000000","open":"20515800000000000000000","openTime":"0001-01-01T00:00:00Z","pair":{"baseToken":"0x4d7eA2cE949216D6b120f3AA10164173615A2b6C","pairName":"BTC/TOMO","quoteToken":"0x0000000000000000000000000000000000000001"},"timestamp":1566536400000,"volume":"58491708435300106"}]}`

open: 20515800000000000000000
close: 20515640000000000000000

But in market trade history of dex as bellow:
![image](https://user-images.githubusercontent.com/16622051/63575390-2827e880-c5b4-11e9-8601-0897ee7de19a.png)
Range of time is not correct. Pls check!

**Comment by nghiatomo** [comment]
fixed
