### ISSUE TITLE
availableBalance = 0

### ISSUE THREAD

**Issue by tiennv3** [tomochain/tomox-sdk#75]
{"data":{"address":"0x8fb1047e874d2e472cd08980ff8383053dd83102","createdAt":"2019-08-23 08:06:05.169 +0000 UTC","favoriteTokens":{},"id":"5d5f9e6d2d9c190af64c9905","isBlocked":false,"tokenBalances":{"0x0000000000000000000000000000000000000001":{"address":"0x0000000000000000000000000000000000000001","availableBalance":"0","balance":"50000000000000000000000","inOrderBalance":"0","symbol":"TOMO"},"0x4d7eA2cE949216D6b120f3AA10164173615A2b6C":{"address":"0x4d7eA2cE949216D6b120f3AA10164173615A2b6C","availableBalance":"0","balance":"50000000000000000000000","inOrderBalance":"0","symbol":"BTC"},"0xC2fa1BA90b15E3612E0067A0020192938784D9C5":{"address":"0xC2fa1BA90b15E3612E0067A0020192938784D9C5","availableBalance":"0","balance":"50000000000000000000000","inOrderBalance":"0","symbol":"ETH"}},"updatedAt":"2019-08-23 08:06:05.169 +0000 UTC"}}

**Comment by nghiatomo** [comment]
fixed in 5fbb8f21a3b19383e12e17b2bb328d553448ca20 commit
