### ISSUE TITLE
Close time and open  time is not correct

### ISSUE THREAD

**Issue by phucngh** [tomochain/tomox-sdk#81]
API:
https://dex.devnet.tomochain.com/api/ohlcv?baseToken=0x4d7eA2cE949216D6b120f3AA10164173615A2b6C&quoteToken=0x0000000000000000000000000000000000000001&timeInterval=1m&from=1566752400&to=1566813267

Return:
{"data":[{"close":"2000000000000000000000","closeTime":"2019-08-26T09:47:38.025Z","count":"3","high":"2000000000000000000000","low":"2000000000000000000000","open":"2000000000000000000000","openTime":"2019-08-26T09:47:06.021Z","pair":{"baseToken":"0x4d7eA2cE949216D6b120f3AA10164173615A2b6C","pairName":"BTC/TOMO","quoteToken":"0x0000000000000000000000000000000000000001"},"timestamp":1566812820000,"volume":"30000000000000000"},{"close":"19000000000000000000000","closeTime":"2019-08-26T09:48:40.022Z","count":"1","high":"19000000000000000000000","low":"19000000000000000000000","open":"19000000000000000000000","openTime":"2019-08-26T09:48:40.022Z","pair":{"baseToken":"0x4d7eA2cE949216D6b120f3AA10164173615A2b6C","pairName":"BTC/TOMO","quoteToken":"0x0000000000000000000000000000000000000001"},"timestamp":1566812880000,"volume":"10000000000000000"}]}

Time interval is 1m but close time and open time is equal. If i change time interval is 5m => range of close time and end time do not equal 5m.

Pls check!

**Comment by nghiatomo** [comment]
remove unnecessary  opentime, closetime
