### ISSUE TITLE
Add release binary for Windows, Mac, linux to travis

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomox-sdk#84]
When: tagged
Trigger: Release binaries to github release page

**Comment by naviat** [comment]
Darwin & windows release build got an error with `crypto/sha3`: 

```
cannot load github.com/ethereum/go-ethereum/crypto/sha3: cannot find module providing package github.com/ethereum/go-ethereum/crypto/sha3
``` 
After investigate: [go-ethereum](https://github.com/ethereum/go-ethereum/) has [upstreamed](https://github.com/ethereum/go-ethereum/issues/19320) Keccak256 into Go's crypto library golang.org/x/crypto/sha3

@nghiatomo Need to fix code and vendor dependencies for windows and darwin release.

**Comment by nghiatomo** [comment]
Build executable windows under linux os:

#apt-get install gcc-multilib
#apt-get install gcc-mingw-w64

CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ GOOS=windows GOARCH=amd64 go build

**Comment by thanhson1085** [comment]
ok, reopen for Hai keep going  his works

**Comment by naviat** [comment]
@nghiatomo Release for windows is ok. update not work with darwin kernel
